name: Security Pipeline

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep --config=p/owasp-top-ten . --error

      - name: Install Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_8.30.0_linux_x64.tar.gz
          tar -xzf gitleaks_8.30.0_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: gitleaks detect --source . --redact --exit-code 1

      - name: Run OWASP Dependency-Check (Docker)
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/src \
            owasp/dependency-check:latest \
            --scan /src \
            --format HTML \
            --out /src/reports
